apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.redash.service: {{ .Release.Name }}-redash
  name: {{ .Release.Name }}-redash-service
spec:
  ports:
  - name: {{ .Release.Name }}-redash
    port: 80
    targetPort: 5000
  selector:
    io.redash.service: nginx
  type: LoadBalancer
